### ISSUE TITLE
Move deprecated utilities to an appropriate subdirectory

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/genomics#30]
Move deprecated utilities to a "mirror" `legacy` subdirectory, pending final removal. The legacy utilities would no longer be installed by `setup.py` but would still be available in the repository if needed again.

- [x] build-indexes/\*.sh (i.e. all scripts) PR #190
- [x] ChIP-seq/run_DESeq.R PR #188
- [x] ChIP-seq/\*.pl (i.e. all Perl scripts) PR #188
- [x] illumina2cluster/auto_process_illumina.sh PR #187
- [x] illumina2cluster/bclToFastq.sh PR #187
- [x] illumina2cluster/rsync_seq_data.py PR #187
- [x] NGS-general/explain_sam_flag.sh PR #195
- [x] NGS-general/remove_mispairs.pl PR #195
- [x] NGS-general/SamStats PR #195
- [x] NGS-general/separate_paired_fastq.pl PR #195
- [x] NGS-general/splitBarcodes.pl PR #195
- [x] QC-pipeline/boxplotps2png.sh PR #197
- [x] QC-pipeline/cleanup_qc.sh PR #197
- [x] QC-pipeline/fastq_stats.sh (used for SOLiD) PR #197
- [x] QC-pipeline/filtering_stats.sh (used for SOLiD) PR #197
- [x] QC-pipeline/qc_boxplotter/ (used for SOLiD) PR #197
- [x] QC-pipeline/run_solid2fastq.sh PR #197
- [x] QC-pipeline/solid_preprocess_filter.sh PR #197
- [x] QC-pipeline/solid_preprocess_truncation_filter.sh PR #197
- [x] QC-pipeline/solid_qc.sh PR #197
- [x] RNA-seq/GFFedit.java PR #189
- [x] RNA-seq/qc_bash_script.sh PR #189
- [x] RNA-seq/Split.java PR #189
- [x] solid/rsync_solid_to_cluster.sh PR #194
- [x] utils/makeBinsFromBed.pl PR #198
- [x] utils/makeRegularBinsFromGenomeTable.R PR #198

These would constitute a first pass; once these are cleared out then the remaining utilities can be revisited and assessed.

Also the documentation under `docs` needs overhauling to reflect the changes, mostly by removing information that is no longer relevant:

- [x] update documentation PR #200
